### ISSUE TITLE
Poets & Writers Series Page

### ISSUE THREAD

**Issue by saltedbones** [TULiberalArts/Creative-Writing#1]
We need this page to be populated with events featuring upcoming readings.  It will have a blurb at the top. It will be similar to the existing page except dynamic. 

http://www.cla.temple.edu/english/creativewriting/poets-writers-series/

**Comment by tu-chill** [comment]
aye

**Comment by CVE82** [comment]
This site has an events feed on the homepage which will feature the programs events, including upcoming readings. .
