### ISSUE TITLE
Dual Degree BA/MA in English Tab

### ISSUE THREAD

**Issue by saltedbones** [TULiberalArts/Creative-Writing#2]
Just a reminder  to make a new tab and page so the undergraduate page isn't so looooong. Also, it just makes sense. We did that for Public Policy. It incorporates both undergrad and grad info.

**Comment by CVE82** [comment]
Done.

**Comment by saltedbones** [comment]
Thanks Moo (that's who your picture is of) ;)

**Comment by CVE82** [comment]
LMAO you got it! #dying #the Moo
